name: CI/CD for Restaurant App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Run tests
      run: |
        source venv/bin/activate
        # Add your test command here, for example:
        python -m unittest discover

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/restaurant_app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/restaurant_app:latest

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: docker

  #   steps:
  #   - name: Deploy to server
  #     env:
  #       SSH_KEY: ${{ secrets.SSH_KEY }}
  #     run: |
  #       echo "$SSH_KEY" | tr -d '\r' | ssh-add -
  #       ssh -o StrictHostKeyChecking=no user@your_server_ip "cd /path/to/your/app && docker-compose pull && docker-compose up -d --build"
